version: '3.8'
services:
  db:
    image: postgres:12.9-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PGUSER:-postgres}
      - POSTGRES_PASSWORD=${PGPASSWORD:-tehsecure}
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - usher-db
  mockidentityprovider-server:
    image: node:14.21.1-alpine
    expose: [3002]
    entrypoint: ["sh", "/app/scripts/run_for_development_mockidentityprovider.sh"]
    ports:
      - 3002:3002
    volumes:
      - ./:/app
    networks:
      main:
        aliases:
          - mockidentityprovider
          - idp.dmgt.com.mock
          - branded-idp-alias.dmgt.com.mock
          - notwhitelisted.labs.dmgt.com.mock
          - whitelisted-but-not-aliased.labs.dmgt.com.mock
          # These should appear under *.localhost
networks:
  main:
