include:
  - docker-compose-ci.yml

services:
  usher-server:
    image: node:20-alpine
    expose: [3001, 9229]
    entrypoint: ["sh", "/app/scripts/run_for_development.sh"]
    depends_on: [db]
    ports:
      - 3001:3001
      - 9229:9229
    volumes:
      - ./:/app
    environment:
      - PGURI=${USHER_PGURI:-postgres://postgres:tehsecure@usher-db:5432/postgres?sslmode=disable}
    links:
      - "mockidentityprovider-server:idp.dmgt.com.mock.localhost"
      - "mockidentityprovider-server:branded-idp-alias.dmgt.com.mock.localhost"
      - "mockidentityprovider-server:notwhitelisted.labs.dmgt.com.mock.localhost"
      - "mockidentityprovider-server:whitelisted-but-not-aliased.labs.dmgt.com.mock.localhost"
    networks:
      main:
        aliases:
          - usher-server
    restart: on-failure
